version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - logs:/app/logs:z
      - config:/app/instance:z
      - uploads:/app/static/uploads:z
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./docker/nginx/certs:/etc/nginx/certs:z
    depends_on:
      - flask
    networks:
      - app-network

volumes:
  pgdata:
  logs:
  config:
  uploads:
networks:
  app-network:
